all: aleatorios todos todos2

aleatorios: aleatorios.c
	gcc -o aleatorios aleatorios.c

todos: todos.c
	gcc -o todos todos.c

todos2: todos2.c
	gcc -o todos2 todos2.c

clean:
	rm -rf aleatorios todos todos2
